; PlatformIO Project Configuration File
; ESP32-S3 (N16R8) IoMT Hardware Diagnostic & Cloud Telemetry

[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Serial Monitor & Upload Speeds
monitor_speed = 115200
upload_speed = 460800

; Release GPIO 0
monitor_dtr = 0
monitor_rts = 0
monitor_filters = 
    esp32_exception_decoder
    direct

; Configure 16MB Flash & 8MB Octal-PSRAM
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.arduino.memory_type = qio_opi

; Route Serial to the UART port (COM6)
build_flags = 
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0
    -DARDUINO_USB_CDC_ON_BOOT=0

; Required Sensor & Cloud Libraries
lib_deps =
    adafruit/Adafruit SSD1306 @ ^2.5.13
    adafruit/Adafruit GFX Library @ ^1.11.11
    adafruit/Adafruit MPU6050 @ ^2.2.6
    adafruit/Adafruit Unified Sensor @ ^1.1.14
    adafruit/Adafruit MLX90614 Library @ ^2.1.5
    sparkfun/SparkFun MAX3010x Pulse and Proximity Sensor Library @ ^1.1.2
    bblanchon/ArduinoJson @ ^7.3.0